# Generated by Django 3.2 on 2023-07-30 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(db_index=True, max_length=20)),
                ('region_num', models.IntegerField(unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200)),
            ],
            options={
                'verbose_name': 'region_name',
                'verbose_name_plural': 'regions_name',
                'ordering': ['region_name'],
            },
        ),
        migrations.AddField(
            model_name='board',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='info_image',
            field=models.ImageField(upload_to='community/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='boards.regioncategory'),
        ),
    ]
