# Generated by Django 3.2 on 2023-08-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_cardnews_cardscrap_imagemulti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemulti',
            name='images',
        ),
        migrations.AddField(
            model_name='imagemulti',
            name='image1',
            field=models.ImageField(null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='imagemulti',
            name='image2',
            field=models.ImageField(null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='imagemulti',
            name='image3',
            field=models.ImageField(null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='imagemulti',
            name='image4',
            field=models.ImageField(null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagemulti',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
