# Generated by Django 3.2 on 2023-08-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20230809_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemulti',
            name='image5',
            field=models.ImageField(null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='imagemulti',
            name='image6',
            field=models.ImageField(null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
    ]
