# Generated by Django 3.2 on 2023-08-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20230809_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemulti',
            name='image10',
            field=models.ImageField(null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='imagemulti',
            name='image11',
            field=models.ImageField(null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='imagemulti',
            name='image7',
            field=models.ImageField(null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='imagemulti',
            name='image8',
            field=models.ImageField(null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='imagemulti',
            name='image9',
            field=models.ImageField(null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
    ]
