# Generated by Django 3.2 on 2023-08-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20230809_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemulti',
            name='description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemulti',
            name='description_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
