# Generated by Django 3.2 on 2023-08-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20230809_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemulti',
            name='sub_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemulti',
            name='sub_title2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemulti',
            name='sub_title3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
