# Generated by Django 3.2 on 2023-08-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20230809_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerwinner', models.ImageField(null=True, upload_to='banner/%Y/%m/%d')),
            ],
        ),
    ]
