# Generated by Django 3.2 on 2023-08-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
