# Generated by Django 3.2 on 2023-08-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_banner_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemulti',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagemulti',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagemulti',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagemulti',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagemulti',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagemulti',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagemulti',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagemulti',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagemulti',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagemulti',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagemulti',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
    ]
