# Generated by Django 3.2 on 2023-08-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20230809_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemulti',
            name='image1',
            field=models.ImageField(null=True, upload_to='cardnews/%Y/%m/%d'),
        ),
    ]
