# Generated by Django 3.2 on 2023-08-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_auto_20230809_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='info_image',
            field=models.ImageField(null=True, upload_to='community/%Y/%m/%d'),
        ),
    ]
