# Generated by Django 3.2 on 2023-08-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_alter_board_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='info_image',
            field=models.ImageField(blank=True, null=True, upload_to='community/%Y/%m/%d'),
        ),
    ]
