# Generated by Django 3.2 on 2023-08-14 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_regionstar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cd', models.IntegerField()),
                ('title_nm', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardnews_behavior', to='boards.cardnews')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cardnews/%Y/%m/%d')),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior', to='boards.behavior')),
            ],
        ),
    ]
