# Generated by Django 3.2 on 2023-08-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0019_behavior_behaviorimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionstar',
            old_name='star',
            new_name='starred',
        ),
    ]
