# Generated by Django 3.2 on 2023-08-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0020_rename_star_regionstar_starred'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegionStar',
        ),
    ]
