# Generated by Django 3.2 on 2023-08-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0021_delete_regionstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioncategory',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
